# Generated by Django 6.0.4 on 2026-04-20 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('dni', models.CharField(blank=True, max_length=9, verbose_name='DNI')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=70, verbose_name='Apellido')),
                ('address', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('obs', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fichaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('in_datetime', models.DateTimeField(verbose_name='Entrada')),
                ('out_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Salida')),
                ('notes', models.CharField(null=True, verbose_name='Notas')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
