spring.application.name=GestionFichajes
spring.datasource.url=jdbc:postgresql://localhost:5432/db_almarsa_backend
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true